# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1562783b62c5bdcafe7e2e579bedbf01"
name = "snap2shop"
application_url = "https://snap2shop-visual-search.onrender.com"
embedded = true
handle = "snap2shop-1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://snap2shop-visual-search.onrender.com/auth/callback",
  "https://snap2shop-visual-search.onrender.com/auth/shopify/callback",
  "https://snap2shop-visual-search.onrender.com/api/auth/callback"
]

[app_proxy]
url = "http://localhost:3000/apps/proxy"
subpath = "api"
prefix = "apps"

[pos]
embedded = false
