# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1562783b62c5bdcafe7e2e579bedbf01"
name = "snap2shop"
application_url = "https://shipped-tier-labels-benjamin.trycloudflare.com"
embedded = true
handle = "snap2shop-1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://shipped-tier-labels-benjamin.trycloudflare.com/auth/callback", "https://shipped-tier-labels-benjamin.trycloudflare.com/auth/shopify/callback", "https://shipped-tier-labels-benjamin.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://shipped-tier-labels-benjamin.trycloudflare.com/apps/proxy"
subpath = "api"
prefix = "apps"
